name: ci-nullplatform
on:
  push:
    branches:
      - main
      - feat/*
permissions:
  id-token: write
  contents: read
  packages: read
env:
  NULLPLATFORM_API_KEY: ${{ secrets.NULLPLATFORM_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Install nullplatform cli
        run: curl https://cli.nullplatform.com/install.sh | sh
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Start nullplatform CI
        run: np build start
  build:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        asset: [docker-image, cron]
    steps:
      - name: Install nullplatform cli
        run: curl https://cli.nullplatform.com/install.sh | sh
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASSET_TYPE: ${{ matrix.asset }}
        run: make build-${{ matrix.asset == 'docker-image' && 'docker' || matrix.asset }}
      - name: Push asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASSET_TYPE: ${{ matrix.asset }}
        run: make push
    outputs:
      status: ${{ contains(fromJSON('["failure", "cancelled"]'), job.status) && 'failed' || 'successful' }}
  finalize:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Install nullplatform cli
        run: curl https://cli.nullplatform.com/install.sh | sh
      - name: End nullplatform CI
        run: np build update --status ${{ needs.build.outputs.status }}